steps:
- task: Bash@3
  displayName: '[Artifact] generate Pulumi config'
  inputs:
    targetType: 'inline'
    script: |
      cat > $(PULUMI_CONFIG_FILE) <<EOF
      config:
        balthazar:apmPublisherEmail: $(APM_PUBLISHER_EMAIL)
        balthazar:apmPublisherName: $(APM_PUBLISHER_NAME)
        balthazar:authOpenIdConfigUrl: $(AUTH_OPENID_CONFIG_URL)
        balthazar:authEndpoint: $(AUTH_ENDPOINT)
        balthazar:authAudience: $(AUTH_AUDIENCE)
        balthazar:domainUrl: $(DOMAIN_URL)
        azure:location: $(AZURE_LOCATION)
      EOF
    workingDirectory: '$(Agent.BuildDirectory)/drop/Deployment'       