trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:  
- stage: build_and_preview
  jobs:
  - job: build_and_preview
    displayName: 'Build and preview deployment'
    steps:
    - task: DotNetCoreCLI@2
      displayName: '[API] dotnet publish'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'API/API.fsproj'
        zipAfterPublish: false
        modifyOutputPath: false
    - task: Npm@1
      displayName: '[Web] npm install'
      inputs:
        command: 'install'
        workingDir: 'Web'
    - task: Npm@1
      displayName: '[Web] npm run build'
      inputs:
        command: 'custom'
        workingDir: 'Web'
        customCommand: 'run build'
    - task: Pulumi@1
      inputs:
        azureSubscription: 'Azure'
        command: 'preview'
        cwd: "Deployment"
        stack: "fajrvehr/balthazar/dev"
      env:
        PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
- stage: deploy
  jobs:
  - deployment: deploy  
    displayName: 'Deploy'
    environment: 'BalthazarTest'    
    strategy:
      runOnce:
        deploy:    
          steps:
          - task: Pulumi@1
            inputs:
              azureSubscription: 'Azure'
              command: up
              cwd: "Deployment"
              args: "--yes"
              stack: "fajrvehr/balthazar/test"
            env:
              PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)              




