trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:  
- stage: build_and_preview
  jobs:
  - job: build_and_preview
    displayName: 'Build and preview deployment'
    steps:
    - task: DotNetCoreCLI@2
      displayName: '[API] dotnet publish'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'API/API.fsproj'
        zipAfterPublish: false
        modifyOutputPath: false
    - task: Npm@1
      displayName: '[Web] npm install'
      inputs:
        command: 'install'
        workingDir: 'Web'
    - task: Npm@1
      displayName: '[Web] npm run build'
      inputs:
        command: 'custom'
        workingDir: 'Web'
        customCommand: 'run build'
    - task: CopyFiles@2
      displayName: '[Artifact] copy API output'
      inputs:
        SourceFolder: 'API/bin/Debug/netcoreapp3.1/publish'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/API/bin/Debug/netcoreapp3.1/publish'
    - task: CopyFiles@2
      displayName: '[Artifact] copy Web output'
      inputs:
        SourceFolder: 'Web/dist'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Web/dist'
    - task: CopyFiles@2
      displayName: '[Artifact] copy Deployment output'
      inputs:
        SourceFolder: 'Deployment'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Deployment'
    - task: Bash@3
      displayName: '[Artifact] generate Pulumi config'
      inputs:
        targetType: 'inline'
        script: |
          cat > $(PULUMI_CONFIG_FILE) <<EOF
          config:
            balthazar:apmPublisherEmail: $(APM_PUBLISHER_EMAIL)
            balthazar:apmPublisherName: $(APM_PUBLISHER_NAME)
            balthazar:authOpenIdConfigUrl: $(AUTH_OPENID_CONFIG_URL)
            balthazar:authEndpoint: $(AUTH_ENDPOINT)
            balthazar:authAudience: $(AUTH_AUDIENCE)
            azure:location: $(AZURE_LOCATION)
          EOF
        workingDirectory: '$(Build.ArtifactStagingDirectory)/Deployment'
    - task: PublishBuildArtifacts@1
      displayName: '[Artifact] publish'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: Pulumi@1
      displayName: '[Pulumi] preview'
      inputs:
        azureSubscription: 'Azure'
        command: 'preview'
        cwd: "$(Build.ArtifactStagingDirectory)/Deployment"
        stack: "$(PULUMI_STACK)"
      env:
        PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
- stage: deploy
  jobs:
  - deployment: deploy  
    displayName: 'Deploy'
    environment: 'BalthazarTest'    
    strategy:
      runOnce:
        deploy:    
          steps:
          - task: Pulumi@1
            displayName: '[Pulumi] up'
            inputs:
              azureSubscription: 'Azure'
              command: up
              cwd: "$(Agent.BuildDirectory)/drop/Deployment"
              args: "--yes"
              stack: "$(PULUMI_STACK)"
            env:
              PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)




